version: '3.8'

services:
  nginx_proxy:
    build:
      context: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt/live/jeremymark.ca-0002/fullchain.pem:/etc/ssl/certs/jeremymark.ca/fullchain.pem:ro
      - /etc/letsencrypt/live/jeremymark.ca-0002/privkey.pem:/etc/ssl/private/jeremymark.ca/privkey.pem:ro
      - /etc/letsencrypt/live/spotify.jeremymark.ca-0002/fullchain.pem:/etc/ssl/certs/spotify.jeremymark.ca/fullchain.pem:ro
      - /etc/letsencrypt/live/spotify.jeremymark.ca-0002/privkey.pem:/etc/ssl/private/spotify.jeremymark.ca/privkey.pem:ro
    networks:
      - net
    depends_on:
      - spotify_api
      - jeremymark_ca

  spotify_api:
    build:
      context: ./spotify_api
    image: spotify_api
    container_name: spotify_api
    env_file:
      - ./spotify_api/.env
    expose:
      - "3002"
    networks:
      - net

  jeremymark_ca:
    build:
      context: .
    image: jeremymark_ca
    container_name: jeremymark_ca
    expose:
      - "3001"
    networks:
      - net

networks: 
  net:
    driver: bridge