version: '3.8'

services:
  jeremymark_ca:
    build:
      context: .
      dockerfile: Dockerfile
    image: jeremymark_ca
    container_name: jeremymark_ca
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/jeremymark.ca/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/jeremymark.ca/privkey.pem:/etc/ssl/private/privkey.pem:ro